---
# This playbook assumes one of two groups are defined in the inventory
#
# "snapshot" group pulls from the Nexus snapshot repository
#
# "release" group pulls from the Nexus release repository
#
# Example snapshot inventory:
#
# [snapshot]
# cprappcop821v ansible_ssh_user=jboss
#
# You supply this inventory using the Jenkins Ansible plugin configuration
#
#
- hosts: all
  sudo: yes
  gather_facts: false

  tasks:

  - name: Create app log directory
    file: path={{ app_log_path }} state=directory  owner={{app_owner}} group={{app_group}}

  - name: Create app dir
    file: path={{ app_path }} state=directory  owner={{app_owner}} group={{app_group}}

  - name: Create app properties
    template: src=prop.template dest={{ app_path }}/{{ app_name }}.properties owner={{app_owner}} group={{app_group}}

  - name: Download app from nexus
    sudo: no
    nexus:
          nexus=http://dev.build.cpr.dk/nexus
          repository={{repository}}
          force=yes
          artifactId=dk.cpr.dar:{{artifact_name}}:{{pomVersion}}
          extension=jar
    register: download
    delegate_to: localhost

  - name: Install app
    copy: src={{download.dest}}
           dest={{ app_path }}/{{download.filename}} owner={{app_owner}} group={{app_group}} mode=755

  - name: Create app conf
    template: src=conf.template dest={{ app_path }}/{{ download.filename | replace('.jar', '.conf') }} owner={{app_owner}} group={{app_group}}

  - name: Create symlink
    file: src={{ app_path }}/{{download.filename}} dest=/etc/init.d/{{app_name}} state=link

  - name: Copy logrotate config
    template: src=logrotate.conf dest=/etc/logrotate.d/{{app_name}}

  - name: Start app
    service: name={{ app_name }} state=restarted

